version: "3"

services:
  recipes-web:
    build: ./recipes-web
    ports:
      - "3000:3000"
    depends_on:
      - recipes-api
    environment:
      - REACT_APP_API_URL=http://recipes-api:8080

  recipes-api:
    build: ./recipes-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - MONGO_DATABASE=recipes
      - REDIS_URI=redis:6379
      - CORS_ORIGIN=http://localhost:3000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
    mongodb-data: